### PR TITLE
Adding base version of BOAT team

### PR DESCRIPTION
**Pull request by valentina-s**
Each member still needs to populate their profile and update their picture if they do not like it. @leewujung I believe I need permissions to add the Preview label and check if it looks right.

### CODE REVIEW

**Comment by leewujung** [comment]
Ok, I slapped on the preview label. And just added the admin team to maintainer, so you should be able to do that in the future.

**Comment by leewujung** [comment]
There seems to be some bugs so the preview did not finish building.

**Comment by leewujung** [comment]
also I'll merge #2 so you can change the target to `main`, and we can work against that for additional PRs.

**Comment by valentina-s** [comment]
I fixed some issues and changed to base to main so it should be good now.

**Comment by leewujung** [comment]
Sounds good. I'll merge this so we can change them further.

**Pull request merged**
